name: Python app CI

on:
  push:
    branches: [Faizan]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint

    - name: Code formatting
      run: |
        black app.py

    - name: Linting
      run: |
        pylint --fail-under=-1 app.py

    - name: Code style
      run: |
        pycodestyle --show-source --show-pep8 app.py

    - name: Run the web application
      run: |
        python app.py
        background: yes
