name: Python app CI

on:
  push:
    branches: [Faizan]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint

    - name: Code formatting
      run: |
        make format

    - name: Linting
      run: |
        make lint

    - name: Code style
      run: |
        make codestyle

    - name: Run the web application
      run: |
        make execute
        background: yes
